#!/bin/bash
# git-remotev
# List all remote sources
set -euo pipefail
for r in `ls -d */` ; do
    r=${r%?}
    if [[ -d "$r/.git" ]]; then
        (
            cd $r
            git remote -v | tail -1 | awk '{print $2}'
        )
    fi
done
exit 0
