#!/bin/bash
# git-statall
# Status all repos
set -euo pipefail
for r in `ls -1` ; do
    if [[ -d "$r/.git" ]]; then
        (
            printf "%-50s" "$r"
            cd $r
            git status | tr '\n' ' '
            printf "\n"
        )
    fi
done
