#!/bin/bash
# days
# Print number of days between 2 dates or today and any specific date

OSDist=$(uname | tr [A-Z] [a-z])
if [[ "$OSDist" == "darwin" ]]; then
    Date=$(which gdate)
    if [[ -z "$Date" ]]; then
        printf "Install GNU /usr/local/bin/gdate\n"
        exit 1
    fi
else
    Date=$(which date)
fi

if [[ -z "$1" || -z "$(echo $1 | grep -Eo '[0-9]{4}-[0-9]{2}-[0-9]{2}')" ]]; then
    printf "Usage: $(basename $0) 2121-01-03\n"
    exit 1
fi

Now=$($Date +%s)
Target=$($Date +%s --date "$1")
Dif=$(($Target-$Now))
Days=$(($Dif / 86400)) # 86400 seconds in a day
echo ${Days#-}

exit 0
# Todo: Rewrite into simple Go exec

if 1 date:
  abort if single date is NOT valid yyyy-mm-dd
  date1 = (now, in epoch sec)
  date2 = given date in epoch sec
    
if 2 dates:
  abort if either date is NOT valid
  date1 = in epoch sec
  date2 = in epoch sec

else:
  usage

diff = ABS(date2 - date1)
days = diff / 86400 and fraction of day

