#!/bin/bash
# screencapture
# Adjust macOS SHIFT-CMD-4 screen capture settings

defaults write com.apple.screencapture location ~/Downloads
defaults write com.apple.screencapture type jpg
defaults write com.apple.screencapture name "screenshot"
defaults write com.apple.screencapture include-date -bool false
defaults write com.apple.screencapture disable-shadow -bool false
killall SystemUIServer
