#!/bin/bash
# setdnswork

IF="Wi-Fi"
printf "==> Updating '$IF' interface DNS settings:\n"
printf "BEFORE ============\n"
sudo networksetup -getdnsservers    "$IF"
sudo networksetup -getsearchdomains "$IF"

sudo networksetup -setdnsservers    "$IF" 10.201.8.63 8.8.8.8
sudo networksetup -setsearchdomains "$IF" advancemags.com aws.conde.io
sudo killall -HUP mDNSResponder

printf "AFTER =============\n"
sudo networksetup -getdnsservers    "$IF"
sudo networksetup -getsearchdomains "$IF"

IF="Thunderbolt Ethernet"
printf "==> Updating '$IF' interface DNS settings:\n"
printf "BEFORE ============\n"
sudo networksetup -getdnsservers    "$IF"
sudo networksetup -getsearchdomains "$IF"

sudo networksetup -setdnsservers    "$IF" 10.201.8.63 8.8.8.8
sudo networksetup -setsearchdomains "$IF" advancemags.com aws.conde.io
sudo killall -HUP mDNSResponder

printf "AFTER =============\n"
sudo networksetup -getdnsservers    "$IF"
sudo networksetup -getsearchdomains "$IF"

exit 0
